import type { Metadata } from "next";
import "@/styles/global.css";
import Header from "../shared/components/layout/Header";
import ModalContainer from "@/shared/components/ui/ModalContainer";
import AuthHydrator from "@/shared/components/hydrator/AuthHydrator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthHydrator />
        <Header />
        <ModalContainer />
        {children}
      </body>
    </html>
  );
}
