import type { Metadata } from "next";
import "@/styles/global.css";
import Header from "../shared/components/layout/Header";
import { ModalProvider } from "@/shared/components/ui/ModalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
